signage/config/routes.rb
Signage::Application.routes.draw do
  resources :merchants
  resources :sessions, only: [:new, :create, :destroy]
  
  root  'basic_pages#home'
  match '/signup',  to: 'merchants#new',            via: 'get'
  match '/signin', to: 'sessions#new', via:'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'basic_pages#help',    via: 'get'
  match '/about',   to: 'basic_pages#about',   via: 'get'
  match '/contact', to: 'basic_pages#contact', via: 'get'
  

end

signage/app/models/merchant.rb
class Merchant < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  validates :company, presence: true
  validates :location, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def Merchant.new_remember_token
    SecureRandom.urlsafe_base64
  end
  def Merchant.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  private
  def create_remember_token
    self.remember_token = Merchant.encrypt(Merchant.new_remember_token)
  end
end

signage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

signage/app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

signage/app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def new
    @merchant=Merchant.new
  end
  def show
    @merchant=Merchant.find(params[:id])
  end
  def create
    @merchant=Merchant.new(merchant_params)    
    if @merchant.save
      flash.now[:success] = "Account Created!"
      render '/sessions/new'
    else
      render 'new'
    end
  end
  private
  def merchant_params
    params.require(:merchant).permit(:name, :email, :password,
                                   :password_confirmation, :location, :company)
  end
    
end

signage/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    merchant = Merchant.find_by(email: params[:session][:email].downcase)
    if merchant && merchant.authenticate(params[:session][:password])
      sign_in merchant
      redirect_to merchant
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

signage/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
  base_title = "Signage Shoppo"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
end
end

signage/app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

signage/app/helpers/merchants_helper.rb
module MerchantsHelper
end

signage/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(merchant)
    remember_token = Merchant.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    merchant.update_attribute(:remember_token, Merchant.encrypt(remember_token))
    self.current_merchant = merchant
  end
  def current_merchant=(merchant)
    @current_merchant = merchant
  end
  def current_merchant
    remember_token = Merchant.encrypt(cookies[:remember_token])
    @current_merchant ||= Merchant.find_by(remember_token: remember_token)
  end
  def signed_in?
    !current_merchant.nil?
  end
  def sign_out
    self.current_merchant = nil
    cookies.delete(:remember_token)
  end
end

signage/app/views/basic_pages/about.html.erb
<h2>Who are We?</h2>
<p>We are Shoppo</p>

signage/app/views/basic_pages/contact.html.erb
<h2>Contact</h2>
<p>Call me at 8144064012</p>

signage/app/views/basic_pages/help.html.erb
<h2>How to use Shoppo</h2>
<p>Search for products to buy</p>

signage/app/views/basic_pages/home.html.erb
<p>
  <h2>Shoppo Product Search</h2>
  <input type="text" id="searchItem" name="searchItem" />
  <input type="submit" id="searchSubmit" value="Search" />
  <div id="merchantList"></div>
</p>

signage/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright of Shoppo
  </small>
</footer>

signage/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <h1>Shoppo</h1>
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
	  <li><%= link_to "About", about_path %></li>
	  <li><%= link_to "Contact Us", contact_path %></li>
          <% if signed_in? %>
          <li><%= link_to "Profile", current_merchant %></li>
          <li><%= link_to "Settings", '#' %></li>
          <li><%= link_to "Sign out", signout_path, method: "delete" %>  </li>
          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
	  <li><%= link_to "Register", signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

signage/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

signage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

signage/app/views/merchants/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@merchant) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>
      
      <%= f.label :company %>
      <%= f.text_field :company %>
      
      <%= f.label :location %>
      <%= f.text_field :location %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

signage/app/views/merchants/show.html.erb
<% provide(:title, @merchant.name) %>
<h1><%= @merchant.name %></h1>

signage/app/views/shared/_error_messages.html.erb
<% if @merchant.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@merchant.errors.count, "error") %>.
    </div>
    <ul>
    <% @merchant.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>